import type { Meeting, Job } from '@/types'

export const MOCK_MEETINGS: Meeting[] = [
  {
    id: 'm1',
    jobId: 'j1',
    title: 'Q3 Product Roadmap Planning',
    durationSeconds: 3612,
    languagesDetected: ['en', 'ur'],
    speakerCount: 3,
    createdAt: new Date(Date.now() - 2 * 86400 * 1000).toISOString(),
    transcript: [
      { start: 0, end: 8.5, speaker: 'SPEAKER_00', text: 'Good morning everyone. Let\'s start with the Q3 roadmap discussion.', language: 'en' },
      { start: 9.1, end: 18.3, speaker: 'SPEAKER_01', text: 'ہاں، میں نے پچھلے sprint کے نتائج تیار کر لیے ہیں۔ Performance metrics بہت اچھی ہیں۔', language: 'ur' },
      { start: 19.0, end: 28.7, speaker: 'SPEAKER_02', text: 'Great. I think we should focus on the mobile app first. The user retention data shows that\'s where we\'re losing customers.', language: 'en' },
      { start: 29.5, end: 40.2, speaker: 'SPEAKER_00', text: 'Bilkul sahi. Mobile-first approach should be our priority. Let\'s allocate 60% of sprint capacity there.', language: 'ur' },
      { start: 41.0, end: 52.8, speaker: 'SPEAKER_01', text: 'I agree. Also, the API response times need improvement. We\'re seeing 2-3 second delays on peak hours.', language: 'en' },
      { start: 53.5, end: 65.0, speaker: 'SPEAKER_02', text: 'Ahmed bhai, kya aap backend optimization ka kaam le sakte hain? Next sprint mein complete karna hai.', language: 'ur' },
    ],
    minutesEn: `## Meeting Minutes

**Date:** Not specified  
**Attendees:** Person 1, Person 2, Person 3  
**Duration:** 1:00:12

### Agenda / Topics Discussed
- Q3 Product Roadmap
- Mobile app strategy
- API performance issues
- Sprint capacity allocation

### Key Discussion Points

**Mobile App Strategy**  
Person 3 presented user retention data showing mobile as the key churn point. The team agreed to prioritize mobile-first approach with 60% sprint capacity.

**API Performance**  
Person 2 flagged 2-3 second delays during peak hours. Person 3 requested Person 2 to own backend optimization for the next sprint.

### Decisions Made
1. Mobile-first approach adopted for Q3
2. 60% sprint capacity allocated to mobile app
3. Backend optimization assigned to Person 2

### Action Items
| Task | Owner | Deadline |
|------|-------|----------|
| Complete mobile app sprint | Team | End of Q3 |
| Backend API optimization | Person 2 | Next sprint |
| Prepare retention report | Person 3 | This week |

### Next Steps
- Schedule mobile app design review
- Set up API monitoring alerts
- Weekly sync every Monday

---
*Minutes generated by MeetMind AI*`,
    minutesUr: `## میٹنگ کی کارروائی

**تاریخ:** متعین نہیں  
**شرکاء:** شخص 1، شخص 2، شخص 3  
**دورانیہ:** 1:00:12

### ایجنڈا / موضوعات

- تیسری سہ ماہی کا پروڈکٹ روڈ میپ
- موبائل ایپ کی حکمت عملی
- API کارکردگی کے مسائل

### اہم فیصلے
1. موبائل فرسٹ اپروچ اپنانا
2. 60٪ اسپرنٹ کیپیسٹی موبائل ایپ کے لیے

---
*یہ منٹس MeetMind AI نے تیار کیے*`,
    actionItems: [
      { id: 'a1', task: 'Complete mobile app sprint planning and design review', owner: 'Person 1', deadline: 'End of Q3', context: 'Mobile-first approach agreed upon', priority: 'high', isCompleted: false },
      { id: 'a2', task: 'Backend API optimization — reduce peak-hour response time below 500ms', owner: 'Person 2', deadline: 'Next sprint', context: '2-3 second delays observed', priority: 'high', isCompleted: false },
      { id: 'a3', task: 'Prepare user retention analytics report', owner: 'Person 3', deadline: 'This week', context: 'Required for roadmap decisions', priority: 'medium', isCompleted: true },
    ],
    speakers: [
      { id: 's1', speakerKey: 'SPEAKER_00', displayName: 'Person 1', color: '#4f46e5' },
      { id: 's2', speakerKey: 'SPEAKER_01', displayName: 'Person 2', color: '#0ea5e9' },
      { id: 's3', speakerKey: 'SPEAKER_02', displayName: 'Person 3', color: '#8b5cf6' },
    ],
  },
  {
    id: 'm2',
    jobId: 'j2',
    title: 'Weekly Team Standup',
    durationSeconds: 1200,
    languagesDetected: ['en'],
    speakerCount: 4,
    createdAt: new Date(Date.now() - 5 * 86400 * 1000).toISOString(),
    transcript: [],
    minutesEn: `## Meeting Minutes\n\n**Date:** Not specified\n\n### Standup Updates\n- All team members shared progress\n- No blockers reported\n\n---\n*Minutes generated by MeetMind AI*`,
    actionItems: [],
    speakers: [],
  },
]

export const MOCK_JOBS: Job[] = [
  {
    id: 'j3',
    status: 'processing',
    step: 'transcribing',
    progressPct: 45,
    fileName: 'board_meeting_may.mp4',
    fileSizeBytes: 1_200_000_000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
